# Generated by Django 3.0 on 2019-12-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
                ('employee_count', models.PositiveIntegerField()),
                ('foundation_date', models.DateTimeField()),
                ('ceo_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameLibraryApp.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('a', 'Action'), ('r', 'RPG'), ('j', 'Jump n Run')], max_length=1, null=True)),
                ('release_date', models.DateTimeField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameLibraryApp.Developer')),
                ('platform', models.ManyToManyField(blank=True, to='gameLibraryApp.Platform')),
            ],
        ),
    ]
