# Generated by Django 3.0 on 2020-01-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='foundation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.DateField(),
        ),
    ]
